
[Sys]
  num_cpu = 2

[WebSocket]
  ip = "0.0.0.0"
  port = 5678
  name = "ws"
  [WebSocket.log]
    WriteToFile = true
    LogFilePath = "./logs/websocket/"
    ZipTime = 2
    ChannelSize = 25

[Http]
  ip = "0.0.0.0"
  port = 5679
  name = "http"
  [Http.log]
    WriteToFile = true
    LogFilePath = "./logs/http/"
    ZipTime = 2
    ChannelSize = 25
