// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Heart struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heart) Reset()         { *m = Heart{} }
func (m *Heart) String() string { return proto.CompactTextString(m) }
func (*Heart) ProtoMessage()    {}
func (*Heart) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Heart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heart.Unmarshal(m, b)
}
func (m *Heart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heart.Marshal(b, m, deterministic)
}
func (m *Heart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heart.Merge(m, src)
}
func (m *Heart) XXX_Size() int {
	return xxx_messageInfo_Heart.Size(m)
}
func (m *Heart) XXX_DiscardUnknown() {
	xxx_messageInfo_Heart.DiscardUnknown(m)
}

var xxx_messageInfo_Heart proto.InternalMessageInfo

func (m *Heart) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type GetConnid struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConnid) Reset()         { *m = GetConnid{} }
func (m *GetConnid) String() string { return proto.CompactTextString(m) }
func (*GetConnid) ProtoMessage()    {}
func (*GetConnid) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *GetConnid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConnid.Unmarshal(m, b)
}
func (m *GetConnid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConnid.Marshal(b, m, deterministic)
}
func (m *GetConnid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConnid.Merge(m, src)
}
func (m *GetConnid) XXX_Size() int {
	return xxx_messageInfo_GetConnid.Size(m)
}
func (m *GetConnid) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConnid.DiscardUnknown(m)
}

var xxx_messageInfo_GetConnid proto.InternalMessageInfo

func (m *GetConnid) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Heart)(nil), "msg.heart")
	proto.RegisterType((*GetConnid)(nil), "msg.GetConnid")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x92,
	0xe6, 0x62, 0xcd, 0x48, 0x4d, 0x2c, 0x2a, 0x11, 0x12, 0xe2, 0x62, 0x29, 0xc9, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0xb3, 0x95, 0x14, 0xb9, 0x38, 0xdd, 0x53, 0x4b, 0x9c,
	0xf3, 0xf3, 0xf2, 0x32, 0x53, 0x84, 0x44, 0xb8, 0x58, 0x4b, 0xf2, 0xb3, 0x53, 0xf3, 0xc0, 0x2a,
	0x38, 0x83, 0x20, 0x9c, 0x24, 0x36, 0xb0, 0x59, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e,
	0x77, 0xb8, 0xe9, 0x5c, 0x00, 0x00, 0x00,
}
